name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Change this to master if your default branch is master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          package-manager: pnpm